### PR TITLE
Minor tweaks

### PR DESCRIPTION
**Pull request by fosterbrereton**
- Added a gitignore
- Updated some of the commit hashes to more recent versions
- Added a `die` to handle failed compilation
- Renamed `minigzip64` -> `minigzip` in the test script

### CODE REVIEW

**Comment by fosterbrereton** [comment]
Thanks for the great script!

**Review by jsnell — CHANGES_REQUESTED** [review]
Hi,

Thanks for the updates. Are you sure about that change to the cloudflare commit ID? It looks identical to the old baseline (zlib 1.2.8), so you maybe took the commit ID from the master branch, not the gcc.amd64 branch?

**Comment by fosterbrereton** [comment]
Yeah, that's my mistake. I'm looking at the right branch now, but it's HEAD is failing to build because of a required SSE 4.2 dependency. I'll look into the issues a little more, and revert the hash in the meantime.

**Comment by fosterbrereton** [comment]
Hmm, it seems even that commit contains the overly-restrictive SSE call. Well _I'm_ broken, but you shouldn't be.

**Pull request closed without merging**
